### PR TITLE
Please Make Compatible For Android Termux

### PR DESCRIPTION
**Pull request by habibinando**
I Want To Mine With My Phone In Other Pool

### CODE REVIEW

**Comment by aerth** [comment]
That would be nice but this is a pull request. I think you meant to create a new issue. https://github.com/aquachain/aquacppminer/issues/new

**Comment by aerth** [comment]
Also, the phone will not get very much hashrate (maybe in 1000 days you will find a block, or maybe never!)

**Comment by habibinando** [comment]
But i Just want to mine, in other coin i get block, so NO problem about block :), the most important thing for me is hard work :)

**Comment by aerth** [comment]
@habibinando I made a new issue for you: https://github.com/aquachain/aquacppminer/issues/4

**Comment by habibinando** [comment]
Oke thx :)

**Pull request closed without merging**
